language: csharp
branches:
  except:
  - /^[0-9]/
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  include:
    - os: linux
      dist: bionic
      dotnet: 3.0
    - os: osx 
      osx_image: xcode11.2
      dotnet: 3.0.101
      before_install:
        - ulimit -n 4096
script:
  - git fetch --unshallow
  - ./build.sh
